### ISSUE TITLE
Move config into storage

### ISSUE THREAD

**Issue by INCENDE** [CS2103AUG2016-W11-C2/main#123]
Might help to improve the architecture.
Any comments?

**Comment by burnflare** [comment]
@INCENDE Not planning to do? Did you just mean moving the config.json file somewhere else?

**Comment by INCENDE** [comment]
Trying to do something similar to the one with user prefs

**Comment by INCENDE** [comment]
Doesn't seem to work though, since user prefs file path and to do list file path depend on config being loaded first

**Comment by burnflare** [comment]
Ah ok
