### ISSUE TITLE
UI lock up is quite noticeable

### ISSUE THREAD

**Issue by burnflare** [CS2103AUG2016-W11-C2/main#134]
Hey @fanwgwg, I was dogfooding the app today and it feels like there is a noticeable UI lock up after every action is performed in the command bar. No matter what action you type, the moment you hit `return` on the keyboard, the UI locks up for ~0.5 seconds before it performs the action. I originally thought it was only for complex actions but it happens to be doing it consistently for every action we perform.

Could you profile the code that gets called when we hit enter and see if there's a bad `sleep()` or some artificial wait happening somewhere?

**Comment by rachx** [comment]
Resolved
