### ISSUE TITLE
Update add command tests

### ISSUE THREAD

**Issue by rachx** [CS2103AUG2016-W11-C2/main#138]
These methods are empty:

```
LogicManagerTest.java::execute_add_invalidArgsFormat()
LogicManagerTest.java::execute_add_invalidTaskData()
```

In the future, update TestTask, TaskBuilder, TypicalTestTasks etc to support task with time. Add tasks with time in gui tests. Currently, guitest only compare task by name: see TaskCardHandle.java isSameTask

**Comment by burnflare** [comment]
This task should fail: `add something from 8pm`

**Comment by rachx** [comment]
Shifted
