### ISSUE TITLE
CS2101 Presentation Dry Run Feedback

### ISSUE THREAD

**Issue by burnflare** [CS2103AUG2016-W11-C2/main#140]
Using this issue to track what improvements we should make to the app for CS2101 OP2
- The help window didn't show all the commands in one screen, it has a scroll bar and looked ugly. This was on the projector's resolution

**Comment by fanwgwg** [comment]
This really depends on how we want the users to use the help window, but of course I will do sth on the scroll bar to make it nicer. If we want to make the user able to refer to help window when they type, then the help window should not take up the whole scree, as suggested by Rachael, then there needs to be a scroll bar. If we just want to show all commands in one screen, then obviously it will take too much space that the user cannot type and refer to help window at the same time.

**Comment by rachx** [comment]
Over and done with
