### ISSUE TITLE
Usable intro website.

### ISSUE THREAD

**Issue by burnflare** [CS2103AUG2016-W11-C2/main#142]
We have a website now: http://agendum.today

@fanwgwg Could you help in designing the website? [This](https://github.com/t413/SinglePaged) is the static website generator I'm using. All you have to do to make changes is switch over to the [gh-pages branch](https://github.com/CS2103AUG2016-W11-C2/main/tree/gh-pages), make whatever changes you want then push the `gh-pages` to Github. The website will automatically update. You can push into `gh-pages` freely as it's not `master`, so no need to pull request.

Section in the website are basically individual posts inside `_posts/`, you can see the current format there.

Here are some sections I'm thinking of:
- Intro
- Features (shows best features with screenshots)
- Quick start
- About us (Our info + contact details)

**Comment by fanwgwg** [comment]
Just updated!

**Comment by burnflare** [comment]
Feedback:
- Quick start section doesn't look very good. The seperation between the points looks too big. Can make it more compact?
- Festures section: Do you think it's possible to do a two column interface? Maybe do responsive scaling so that on mobile it has 1 column and desktop it has 2 columns. Ignore if too complex.
- About us. Let's standardize. Crop each profile pic to an equally sized circle. Then instead of placing them vertically, split into 4 columns as have each profile on a column. It'll look much more compact that way.

**Comment by fanwgwg** [comment]
But can we split columns with the markdown?

**Comment by rachx** [comment]
done
