### ISSUE TITLE
Autocomplete command keywords

### ISSUE THREAD

**Issue by rachx** [CS2103AUG2016-W11-C2/main#145]
Support autocompletion of command keywords using "tab" in the CLI
Use EditDistanceCalculator?

**Comment by burnflare** [comment]
Reassining to @fanwgwg as I'm not very familiar with the UI and key capture work.

Implementing this will be trivial. When the user hits tab, all you have to do is take the command box, send it to `EditDistanceCalculator.parseString()` and get the `Optional<String>` output. If output `,isPresent()`, then `.get()` the String and replace the command box with that string.

**Comment by fanwgwg** [comment]
Just create PR #146.
But the autocomplete doesn't look very good, cuz the parser only returns result if the user has already typed most. For example, for the `schedule` command, it is only after the user typed `schedul` that it can complete the last `e` for me, which is a bit useless. Is there anyway to improve the parser?

**Comment by burnflare** [comment]
Yup there is. I'll try tweaking the calculator's finer settings and push commits.

**Comment by burnflare** [comment]
Check it out now, it works fantastically
