### ISSUE TITLE
Remove select command and prepare select

### ISSUE THREAD

**Issue by rachx** [CS2103AUG2016-W11-C2/main#152]
This is assuming that we won't need it for google calendar integration @burnflare ?

**Comment by burnflare** [comment]
Don't see how google calendar would need it, the sync will just work in the background by itself. Ok to remove!

**Comment by rachx** [comment]
I think his original idea was you select a task, then the google calendar window with the task pops up

**Comment by burnflare** [comment]
Can remove.
