### ISSUE TITLE
Bugs related to multiple delete

### ISSUE THREAD

**Issue by fanwgwg** [CS2103AUG2016-W11-C2/main#155]
If delete the data storage file and start from 0 tasks, perfrom `add 1`, `add 2`, `add 3`, `add 4`, `add 5`, `add 6`, and then `delete 1-6`, there will be exceptions thrown and these tasks are not deleted.

**Comment by rachx** [comment]
JavaFX?
https://bugs.openjdk.java.net/browse/JDK-8087508
@burnflare

**Comment by rachx** [comment]
Might be resolved by #188 ?
