### ISSUE TITLE
Bug: load and undo previous command

### ISSUE THREAD

**Issue by rachx** [CS2103AUG2016-W11-C2/main#156]
If we have 2 lists: original and fromload
We have been modifying original (therefore backing up old to do lists)
then we load fromload
typo undo => will restore the todolist from orginal in fromload [unintended behavior]

Solutions
1) after loading, clear back up to do list stack
2) implement undo for load/store etc

Thoughts? @burnflare

**Comment by INCENDE** [comment]
I think we should prevent users from undo-ing load

**Comment by burnflare** [comment]
We should consider load and store as 'meta' levels commands. These commands are swapping out the data storage from underneath the app. Usability wise that's kinda like saving a MS Word doc, closing Word then opening Word with another file. Users do not expect commands like undo to work over such meta level commands. We should clear the undo table after every `load`

**Comment by rachx** [comment]
store is fine right? I think we can just make it clear in the user guide.
Can be easily fixed
