### ISSUE TITLE
Commit sample data for testing

### ISSUE THREAD

**Issue by burnflare** [CS2103AUG2016-W11-C2/main#163]
Hey @INCENDE, can you commit a good test seed data into `/data/sample.xml`?

I find myself manually adding data every time I want to test with a big data set and its a waste of time. Can you create a good seed of tasks for us, rename the file to `sample.xml` and commit into the data folder? Then we can all consistently load the same file whenever we wanna do a test with seed data.

**Comment by rachx** [comment]
Can use automated testing to generate the seed data too
