### ISSUE TITLE
Throw DuplicateTaskException for mark/unmark

### ISSUE THREAD

**Issue by rachx** [CS2103AUG2016-W11-C2/main#164]

**Comment by burnflare** [comment]
Hmm, in what scenario can this happen? Update the description?

**Comment by rachx** [comment]
2 tasks are the same if they have the same name, start and end time and completion status.
DuplicateTaskException might be thrown when user adds a duplicate task/rename and reschedule an existing task to result in it.
I left out mark/unmark the last time. So we can
1) add something
2) mark something
3) add something (it is different as it is not completed)
4) mark it (will pass in the current implementation but should there be an exception to be consistent with the rest?)

More generally, should we allow people to 
1) add  2 tasks of the same name?
2) have 2 tasks with the same name/completion status/start and end time?

**Comment by rachx** [comment]
actually, check for adding events as well. something it doesn't work

**Comment by rachx** [comment]
resolved
