### ISSUE TITLE
Things to do for V0.5 (week 13)

### ISSUE THREAD

**Issue by INCENDE** [CS2103AUG2016-W11-C2/main#167]
**Due Monday, 7 Nov 2016, 2359hours**

Add these two new files to the repo (these will be used by our testers when testing your final submission):

\src\test\data\ManualTesting\SampleData.xml : 
- Sample data that can be loaded to your app. Should contain 50+ items covering past and present.

\src\test\data\ManualTesting\TestScript.md : 
- A document explaining the steps to perform manual testing (i.e. manual scripted testing), starting with how to load the sample data.
- Should cover all functionality of the product.
- Should specify the command to type and the expected result (screenshots not required). 
- Limit the test cases to about 20 minutes worth of testing.
## Submission

Source code :
- Push the code to GitHub and tag with the version number. 
- Source code
  - including collated .md files;
  - please ensure the collated .md files are up to date, you will not be allowed to updated them later) 
  - Note that the quality of the code in these .md files accounts for 15 marks of your final score, graded individually.

Executable: 
- upload to IVLE as an exe or jar or zip file (this should not contain source files). 
- File name: [team][project name].jar e.g. [T09-C1][ToDoo Pro].jar 

Documentation:

- Update documentation on GitHub
- Copy paste content into a doc file. Follow this template exactly.
- Save as pdf
- Name it as follows [TEAM_ID][Project Name].pdf e.g. [T09-C1][ToDoo Pro].pdf
- Upload to IVLE.

Warning: When determining the late submission penalty, we take the latest submission even if the same exact file was submitted earlier. Do not submit the same file multiple times if you want to avoid unnecessary late submission penalties. 

## Concluding To-dos

- [x] Manual testing folder
- [x] Push updated collation folder @burnflare
- [x] Make a v0.5 release on Github and tag @burnflare
- [x] Zip up Source code
- [x] Executable
- [x] Documentation

**Comment by INCENDE** [comment]
@fanwgwg could you create the test script
You can use my sample data

**Comment by fanwgwg** [comment]
Yup sure!

**Comment by rachx** [comment]
Oh we are done :)
