### ISSUE TITLE
"from", "to" and "by" should be case insensitive as well

### ISSUE THREAD

**Issue by rachx** [CS2103AUG2016-W11-C2/main#169]
Update parsing for add/schedule.
If possible, add other words such as "on" and "at"
Should there be an invalid command if a user specifies a deadline + start/end time?
"add go for a run from 2pm to 4pm by friday" - behavior is not well-defined (anything with by, from and to)

**Comment by burnflare** [comment]
@rachx Can I assign this back to you? Don't think I'll have time to finish this over the weekend given the remaining GCal integration work

**Comment by rachx** [comment]
@burnflare I made from/by/to case insensitive in the improve-test-coverage branch and ensured that if a valid time is provided, it only accepts a deadline or event time (with from and to) not both.

Do check after it is merged into master and compare against the latest user guide in the v0.4 docs pr.

If you find time to refactor the code such that the date time parser output the start and end time, then  we can consider adding "on" and "at"

**Comment by rachx** [comment]
Okay to be addressed by #204
