### ISSUE TITLE
Text should be vertically centralised for tasks without 

### ISSUE THREAD

**Issue by burnflare** [CS2103AUG2016-W11-C2/main#183]
Tasks with timings looks fine:
<img width="438" alt="screen shot 2016-10-31 at 4 35 59 pm" src="https://cloud.githubusercontent.com/assets/104150/19848378/2631807c-9f88-11e6-865a-fefe25bdb187.png">

but tasks without things looks unbalanced:
<img width="453" alt="screen shot 2016-10-31 at 4 36 02 pm" src="https://cloud.githubusercontent.com/assets/104150/19848392/3213db06-9f88-11e6-8b98-832a62fd68fb.png">

the text in these tasks should be vertically centralised

**Comment by fanwgwg** [comment]
#179 Resolved
