### ISSUE TITLE
Show completed date/time for tasks in the done column

### ISSUE THREAD

**Issue by burnflare** [CS2103AUG2016-W11-C2/main#184]
Currently a tasks that's marked as complete looks like this
<img width="422" alt="screen shot 2016-10-31 at 4 38 00 pm" src="https://cloud.githubusercontent.com/assets/104150/19848442/6e2420ba-9f88-11e6-9c07-b993756050b4.png">

It should be updated to look like our [About us](https://github.com/CS2103AUG2016-W11-C2/main/blob/master/README.md). So, the timing shown in a completed task should be the task's completed time, not the actual start/end time in the task.

**Comment by fanwgwg** [comment]
Resolved #179
