### ISSUE TITLE
Browser Panel Removal

### ISSUE THREAD

**Issue by INCENDE** [CS2103AUG2016-W11-C2/main#197]
Should we remove it?
Since we are not using it.

It's the web browser thingy
[source](../tree/master/src/main/java/seedu/agendum/ui/BrowserPanel.java)

**Comment by burnflare** [comment]
![Kill it with fire](http://i.giphy.com/wvFrJa4aWKuvm.gif)

**Comment by fanwgwg** [comment]
Removed in the #103, already merged
