### ISSUE TITLE
Last minute tips (+v0.5rc Feedback)

### ISSUE THREAD

**Issue by cmkumar87** [CS2103AUG2016-W11-C2/main#200]
@burnflare @INCENDE @fanwgwg @rachx 
- Highly recommend to stop any and all dev now.
- Do User acceptance testing. That is, use the jar file with a lot of data and run every command that you plan to show in the demo with different test scenarios. Test all edge case inputs, rare inputs and negative cases. For eg.,  date input of 31st Feb
- Throw any 'nice to have' feature that is imperfect to show in the demo by now from v0.5 product.
- Ensure your app runs on both windows and mac. If not, declare it now so that evaluates can have the right computer to test
- Check your milestones. Assign a member if there are unassigned issues. Remove issues irrelevant to the milestone, especially if they are still open
[will update if I think of more stuff]

**Comment by rachx** [comment]
Hi @cmkumar87,

We are using natty for date time parsing. Just to clarify do we have to make sure that the behavior follows what we listed in our user guide? E.g. natty can read month/day e.g. 01/23 but will read day/month 23/01 incorrectly. We will explicit state it in the user guide
It decides to read 31st feb as 2 Mar and add smth by -2/-2 as 2am of the current day

**Comment by cmkumar87** [comment]
@rachx 
Okay. If you identify a bug in your system is caused by the library, you can either:
- handle it as an exception and recover
- or if handling is difficult (like your case now since you won't know when the user types the illegal input) simply let the user know, at least via the user manual.
  These kinds of issues are generally referred as 'known issues' with a software. That is, they are know but are not being solved due to some constraint such as dependency, lack of manpower, etc
