### ISSUE TITLE
Small UI niceties

### ISSUE THREAD

**Issue by burnflare** [CS2103AUG2016-W11-C2/main#203]
The app currently looks like this on my OS X dock
<img width="53" alt="screen shot 2016-11-05 at 6 42 49 pm" src="https://cloud.githubusercontent.com/assets/104150/20029468/b3a0dd1a-a387-11e6-90ee-3e8b068b3ceb.png">

Could you explore if it's possible to call it Agendum instead of java and change that _ugly_ coffee java icon to our own icon also?

**Comment by fanwgwg** [comment]
Just did some research on this, it says that for the jar file, there is no way to change the icon cuz it is set to be the coffee icon by default. However, to set an icon, we can wrap the jar file into a .exe on window or .app on mac, but I am not sure whether this is allowed in our product scope?

**Comment by burnflare** [comment]
We’ll lose platform compatibility on the same file if we do that. Let’s drop this.
