### ISSUE TITLE
Enhancement: date time issues

### ISSUE THREAD

**Issue by rachx** [CS2103AUG2016-W11-C2/main#208]
We did balance start and end time
But there are some unexpected behavior
e.g. add wedding dinner from 30 oct 2pm to 4pm (today :( )

just make it clear in user guide to specify 30 oct?

**Comment by burnflare** [comment]
Yeah. Not sure what we can do about this. Technically, there is no violation here. 30th October 2pm to November 6th 4pm is valid in my system.

**Comment by burnflare** [comment]
Assigning to @INCENDE to update docs to make this clear

**Comment by rachx** [comment]
I changed it.
Now under the add command:
add attend wedding dinner from 30 Oct 7pm to **30 Oct** 9.30pm

Under date time format
If no year, date or time is specified, the current year, date or time will be used. It is advisable to specify both the date and time.

Helpful tip: With Agendum, you can skip typing the second date only if the deadline/event is **happening some time in the future**
(this holds right?)

**Comment by burnflare** [comment]
Yup it holds, anything in the future, we +1 the end date until its after start date.
