### ISSUE TITLE
Main build failing

### ISSUE THREAD

**Issue by INCENDE** [CS2103AUG2016-W11-C2/main#212]
Same problem i believe as #205 
@burnflare anyway to resolve this 😨

**Comment by burnflare** [comment]
Yup

**Comment by burnflare** [comment]
Do I win the award for first person to break master

**Comment by burnflare** [comment]
I'm exploring options now.
- Disable tests altogether
- Create multiple account and rotate through them for testing
- Make test less exhaustive

**Comment by INCENDE** [comment]
![image](https://cloud.githubusercontent.com/assets/13978186/20037550/8b49b67c-a45c-11e6-9c48-55bbf3379cba.png)
looks like we're not the only ones though

**Comment by burnflare** [comment]
As an emergency patch, I'll disable tests on this file for now to get a green light.

**Comment by burnflare** [comment]
Merged patch into master. Expect a real fix PR shortly

**Comment by rachx** [comment]
smallest code base XD

**Comment by burnflare** [comment]
Gave me a shock, I thought it was broken again
