### ISSUE TITLE
What to do for DEMO

### ISSUE THREAD

**Issue by INCENDE** [CS2103AUG2016-W11-C2/main#217]
Duration: 12 minutes

- to demo the product using the executable submitted,
- on your own laptop,
- using the projector or the TV.
-------

Main points of the demo:

- cover the full range of your product's functionality.
- showcase **how the product improves the user’s workflow** rather than simply describe each feature
- **No need to cover design/implementation details**
- Rehearse the steps well and ensure you can finish the demo within the 12 minutes
- Don’t waste time repeating things the evaluator already knows. 
   - e.g., Jim’s workflow, the purpose of your product, etc.
- **Give more time to stronger features** (i.e. cover mundane/basic features fast).

**[Instead of this]** Jim get’s a call from boss. “Ring ring”, “hello”, “oh hi Jim, can we postpone the meeting?” “Sure”. Jim hang up and curses the boss under his breath. Now he starts typing ..etc. 

**[do this]** If Jim needs to postpone the meeting, he can type … 

It’s not that dramatization is bad or we don’t like it. We simply don’t have enough time for it. 

---

Other points:

- Dress code: Dress as if you **represent a startup company giving a product demo at a technology conference**. The level of formality is up to you, but it is recommended that the whole team dress at the same level.
- Punctuality: **automatic penalty for late arrival**
- Use of slides: Not recommended to use slides. If you do, use them sparingly.
- Use of videos: discouraged. We prefer a live demo.
- Every team member should take part in the demo. However, it's ok for one member to do all the typing.

**Comment by burnflare** [comment]
I think we should work on a new `sample.xml` for tomorrow that's optimised for viewing at 11am on 9th November 2016.

@rachx or @INCENDE Do you wanna work on it and attach here in the comments?
