### ISSUE TITLE
Removal of "tags"

### ISSUE THREAD

**Issue by INCENDE** [CS2103AUG2016-W11-C2/main#24]
@rachx @burnflare @fanwgwg are we going to remove tags from our project entirely?

**Comment by burnflare** [comment]
I don't see tags mentioned at all in our UserGuide. So, I guess yes?

**Comment by burnflare** [comment]
Can we make a decision on this by today? If we decide to remove I'll be making a PR today to execute this

**Comment by INCENDE** [comment]
Approved by @burnflare
