### ISSUE TITLE
Prints usage instructions

### ISSUE THREAD

**Issue by rachx** [CS2103AUG2016-W11-C2/main#29]
Refer to instructions when I forget how to use the app
(Link to the Github user guide or have a short summary similar to address book level 3)

**Comment by fanwgwg** [comment]
Done! Also add `ESC` as shortcut key to close the help window

**Comment by burnflare** [comment]
@fanwgwg Which PR completes this issue?

**Comment by fanwgwg** [comment]
Still in my chagne-ui branch, it is the help window
