### ISSUE TITLE
Deadline support for add command

### ISSUE THREAD

**Issue by rachx** [CS2103AUG2016-W11-C2/main#30]
So that I can keep track of events with defined start and end dates (or deadlines)
Similarly, I should be able to edit and remove start/end time/deadlines so that I can respond to changes accordingly.
- Implement DateTimeParser
- Implement Schedule Command

Note
- Cater for the possibility of task description containing keywords such as ‘from’ ‘to’. e.g., The user can  add the task ‘watch day after tomorrow’ without the software interpreting ‘tomorrow’ as the day for the task.
- Support floating tasks, tasks with deadlines and event with start and end times
- Consider using PrettyTime time parser: http://www.ocpsoft.org/prettytime/nlp/

**Comment by burnflare** [comment]
Working on this now

**Comment by siawyoung** [comment]
Any updates?

**Comment by cmkumar87** [comment]
@rachx @burnflare @INCENDE @fanwgwg if this is a 0.2 milestone task, it should be closed by now. Tasks scheduled for a milestone but not completed will attract penalty.

**Comment by fanwgwg** [comment]
Task completed for 0.2 milestone!
