### ISSUE TITLE
Undo command

### ISSUE THREAD

**Issue by rachx** [CS2103AUG2016-W11-C2/main#31]
so that I can easily correct any accidental mistakes in the last command

**Comment by burnflare** [comment]
My thought of implementing this was: We update `abstract class Command` to add an abstract method called `reverseExecute()`. All `Command` classes would have to implement this method which basically does the exact opposite of what the `execute()` command originally did. Then we can just maintain a stack of Commands and as the user calls 'undo', get the last command from the stack and call `reverseExecute()` on it.
