### ISSUE TITLE
Enhance the UI

### ISSUE THREAD

**Issue by rachx** [CS2103AUG2016-W11-C2/main#39]
Tasks should be nicely laid out so that the user can read the information quickly.
Should reflect the deadline/start time/end time (month + day + time ), the status of completion (completed/uncompleted) and eventually if it is overdue or coming
Add colors to reflect the changes and update spacing

**Comment by fanwgwg** [comment]
I have already pushed the change-ui branch to our repo, can clone and check. However, some functionalities like filtering completed tasks are not implemented yet, so I just left the ui there without actually implementing yet.

**Comment by cmkumar87** [comment]
@rachx @burnflare @INCENDE @fanwgwg if this is a 0.2 milestone task, it should be closed by now. Tasks scheduled for a milestone but not completed will attract penalty.

**Comment by fanwgwg** [comment]
Task completed for 0.2 milestone!
