### ISSUE TITLE
Use java.logger

### ISSUE THREAD

**Issue by burnflare** [CS2103AUG2016-W11-C2/main#53]
Tutor feedback: We should be using a logging framework. The built-in java.logger is a suitable one. Have a standardised decision on when to use each kind of logs {minor, major, critical, etc}.

**Comment by INCENDE** [comment]
I believe we can put this in dev guide as well

**Comment by burnflare** [comment]
Yup! Including the details about what kind of details go into what kind of log level.

**Comment by INCENDE** [comment]
Included in dev guide.
