### ISSUE TITLE
User and developer guides for V0.3

### ISSUE THREAD

**Issue by rachx** [CS2103AUG2016-W11-C2/main#62]
Follow the documentation in the sample project in terms or organization, level of details, etc.
Update User Guide to match what you plan to deliver at V0.5
Update Developer Guide to match your current design or the design you plan to have at V0.5

Note: Please merge Weiguang/Justin PR first
Due by Monday 7pm (do 2101 simultaneously) 

Readme
- [x] Update our UI screenshot (Weiguang)
- [x] Remove link to Learning outcome (Weiguang)

User guide
- [x] Add introduction from CS2101  (Weiguang)
- [x] Add FAQ (Justin)
- [x] Add command summary (Rachael)

User guide features
- [x] Vishnu: adding a task, scheduling, undo 
- [x] Rachael: renaming, deleting, mark and unmarking tasks
- [x] Weiguang: List, find, keyboard shortcuts, help
- [x] Justin: General command format, alias, unalias commands, specifying a data storage location (is load added as well?)

Developer guide
(individually graded, advice is one seq diagram, one class diagram, with justifications)
(might be a good idea to look at collate)
(decide on how we want to store previously entered commands for scrolling and separately for undo which will actually affect the diagrams)
Follow: https://github.com/collate/collate/blob/master/docs/Developer-Guide.md  (Notable API table)

Weiguang
- [x] Introduction
- [x] Setting up
- [x] UI component (add your new classes, consider using inheritance for task card)

Justin
- [x] Appendix A: user stories
- [x] Appendix D: glossary
- [x] Storage component
- [x] Common classes (the description is non-existent)

Vishnu
- [x] Appendix B,C: use cases and non-functional requirement (maybe use cases should be embedded in developer guide)
- [x] Add product survey for Omnifocus?
- [x] Logic component (update design and consider making parser abstract, with date time and individual command parsers after refactoring)
- [x] Implementation

Rachael
- [x] Appendix E: product survey
- [x] High level design
- [x] Model component
- [x] testing and dev ops

Active branch: Update-user-guide-for-v0.3

**Comment by INCENDE** [comment]
I believe this is completed
