### ISSUE TITLE
Update messages

### ISSUE THREAD

**Issue by rachx** [CS2103AUG2016-W11-C2/main#66]
Customise the feedback messages for Agendum
Error message for Add to be updated as well
Make it more user friendly e.g. what task indexes are invalid, what tasks are deleted

**Comment by fanwgwg** [comment]
This is not handled by ui, instead, it is handled by the command execution part in logic. In UI, there is even no way to know what goes wrong, or whether this command is executed succesful or not.

**Comment by rachx** [comment]
Resolved.
Delete/mark/unmark tasks will show the indices and names as a preview
