### ISSUE TITLE
Add bug: Should only care about last ‘by’

### ISSUE THREAD

**Issue by burnflare** [CS2103AUG2016-W11-C2/main#77]
Allow user to add command "drop by school" without throwing an invalid add/date time format exception. (Options: use -by or /by, ignore words enclosed within inverted commas, check if word after by is a time)

**Comment by rachx** [comment]
Other problems: cannot "add top up". I think it is because top starts with to

**Comment by rachx** [comment]
Hey @burnflare , can you double check if there is escape for keywords in the task name?
e.g. the user should be able to use from, by and to and time (e.g. tomorrow) as part of normal text, maybe through the use of special characters etc
and sometimes, it is weird to say from/to or by, maybe "on" can be used instead?
