### ISSUE TITLE
Google Calendar Integration

### ISSUE THREAD

**Issue by INCENDE** [CS2103AUG2016-W11-C2/main#84]
- [x] Only care about events with start&&end time
- [x] On `sync on`, it should push up all tasks
- [x] CRUD should work from Agendum -> GCal
- [ ] Bonus point: CRUD backwards from GCal -> Agendum
- [ ] Bonus point: In Gcal, give a "alert" 10mins before end time

**Comment by burnflare** [comment]
Hey @burnflare you should start on this soon

**Comment by burnflare** [comment]
Prototype by v0.4

**Comment by rachx** [comment]
From Damith's handout:
When you implement a feature, consider all aspects of it. For example, if your plan to implement GCal sync, consider things such as how to store floating tasks in GCal, how to sync older items in GCal with your software, how to sync repeating events, and so on. It is not necessary that you implement all those things. However, you should have considered all those things and you should have good reasons why you chose what you implemented over what you did not implement.

**Comment by burnflare** [comment]
I'll try to get a prototype by Thursday

**Comment by burnflare** [comment]
Got authentication working yesterday. Will post details later today about how I want the workflow of this to work

**Comment by rachx** [comment]
Updates?
Is it only going to work one way on uncompleted events?

**Comment by burnflare** [comment]
Merged #192
