### ISSUE TITLE
Events not properly registering accross midnight

### ISSUE THREAD

**Issue by INCENDE** [CS2103AUG2016-W11-C2/main#87]
![image](https://cloud.githubusercontent.com/assets/13978186/19504790/b4e4f97c-95ef-11e6-96f3-6c17bc0ee0e8.png)

It should be wed 10pm to  thursday 5am

`[USER COMMAND][add hi from 10pm to 5am]`

**Comment by burnflare** [comment]
Can I just add 1 day to the end date in the task if the end date is < than start date?
