### ISSUE TITLE
Tutor feedback: Done column

### ISSUE THREAD

**Issue by burnflare** [CS2103AUG2016-W11-C2/main#88]
Feedback from Damith:
Is the `Done` column practical/useful? Will it be collecting all the done tasks in the last year? What if we just see the done tasks from 'yesterday'.

**Comment by fanwgwg** [comment]
Can we just show this panel in the order of latest completed time

**Comment by burnflare** [comment]
That's a good workaround.

**Comment by rachx** [comment]
What are we going to do about archive?
