### ISSUE TITLE
T9 (V0.3) Feedback

### ISSUE THREAD

**Issue by cmkumar87** [CS2103AUG2016-W11-C2/main#98]
- I think you are okay functionality wise for v0.3. Please try to improve the UI design in the final product. You have GCal integration, etc.. So I think UI is going to change substantially.
- There are other teams like you who have their design similar to address book level 4 and  hence do not have changes to the design. This is okay. But we suggest you to consider the foll.
  - Compare with other alternative designs possible.
  - Add more descriptions e.g. show at least one interaction (i.e. sequence diagrams) within each component. But this doesn't mean to add more verbose text about trivial and unstable things.
  - Use object diagrams to show the object structure at runtime
  - Use activity diagrams and OO domain models where applicable (covered in yesterday's lecture)
  - Explain how they implemented things such as undo/redo (since they weren't given features in AddressBook Level 4)

**Comment by burnflare** [comment]
Thanks!
